[package]
name = "reader"
version = "0.1.0"
edition = "2024"


[dependencies]
epub = "1.2.2"
clap = { version = "4.4", features = ["derive"] }
ansi_term = "0.12.1"
html2text = "0.6.0"
dirs = "5.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"